import cv2
import numpy as np
import matplotlib.pyplot as plt
def analyze_histogram(image_path):
    image = cv2.imread("C:/Users/SAJIN/Pictures/Screenshots/Screenshot (5).png")
    hsv_image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    h, s, v = cv2.split(hsv_image)
    hist_h = cv2.calcHist([h], [0], None, [180], [0, 180])
    hist_s = cv2.calcHist([s], [0], None, [256], [0, 256])
    hist_v = cv2.calcHist([v], [0], None, [256], [0, 256])
    plt.figure(figsize=(10, 6))
    plt.subplot(3, 1, 1)
    plt.plot(hist_h, color='r')
    plt.title('Hue Histogram')
    plt.xlabel('Bins')
    plt.ylabel('Frequency')
    plt.subplot(3, 1, 2)
    plt.plot(hist_s, color='g')
    plt.title('Saturation Histogram')
    plt.xlabel('Bins')
    plt.ylabel('Frequency')
    plt.subplot(3, 1, 3)
    plt.plot(hist_v, color='b')
    plt.title('Value Histogram')
    plt.xlabel('Bins')
    plt.ylabel('Frequency')
    plt.tight_layout()
    plt.show()
analyze_histogram('input_image.jpg')
